export type Asset = {
  name: string
  file: string
  category: string
  description: string
}

export const categories = [
  'All',
  'Instagram',
  'X (Twitter)',
] as const

export const assets: Asset[] = [
  {
    name: 'X Profile Banner — Capital for the Fearless',
    file: '/assets/x/x-header-banner.png',
    category: 'X (Twitter)',
    description: 'Profile header banner. Wide 3:1 — resize to 1500x500 on upload.',
  },
  {
    name: 'X Launch — We Have Arrived',
    file: '/assets/x/launch-announcement.png',
    category: 'X (Twitter)',
    description: 'Marble museum hall — monumental glass TPP logo installation.',
  },
  {
    name: 'X Payout Proof — $120K',
    file: '/assets/x/payout-proof-120k.png',
    category: 'X (Twitter)',
    description: 'Bank vault with gold bars — highest single payout flex.',
  },
  {
    name: 'X Get Funded up to $200K',
    file: '/assets/x/funding-200k.png',
    category: 'X (Twitter)',
    description: 'Desert dunes land-art — six account sizes from $59.',
  },
  {
    name: 'X Payouts in Under 24 Hours',
    file: '/assets/x/payouts-24h.png',
    category: 'X (Twitter)',
    description: 'Lightning bolt payout speed creative. 16:9.',
  },
  {
    name: 'X Flash Sale 50% Off',
    file: '/assets/x/flash-sale-50.png',
    category: 'X (Twitter)',
    description: '50% off promo with code FIRSTTPP. 16:9.',
  },
  {
    name: 'X 90% Profit Split',
    file: '/assets/x/profit-split-90.png',
    category: 'X (Twitter)',
    description: 'Penthouse rooftop at golden hour — keep up to 90% of profits.',
  },
  {
    name: 'X One Step Challenge',
    file: '/assets/x/one-step-challenge.png',
    category: 'X (Twitter)',
    description: 'Mountain summit — one glass step at the peak, funded.',
  },
  {
    name: 'X Milestone — $2.5M Paid',
    file: '/assets/x/milestone-2-5m.png',
    category: 'X (Twitter)',
    description: 'Concert arena with confetti cannons — $2.5M+ paid milestone.',
  },
  {
    name: 'X Giveaway — Funded Accounts',
    file: '/assets/x/giveaway-funded-accounts.png',
    category: 'X (Twitter)',
    description: 'White studio, five glass gift boxes — 5x $10K giveaway.',
  },
  {
    name: 'X Discipline Pays',
    file: '/assets/x/discipline-pays.png',
    category: 'X (Twitter)',
    description: 'Empty gym at dawn — discipline pays typography sculpture.',
  },
  {
    name: 'X Global Community',
    file: '/assets/x/global-community.png',
    category: 'X (Twitter)',
    description: 'Earth from space at night — 10,000+ traders, 150+ countries.',
  },
  {
    name: 'X Start With Only $9',
    file: '/assets/x/start-with-only-9.png',
    category: 'X (Twitter)',
    description: 'Coffee shop counter — skip one coffee, start with $9.',
  },
  {
    name: 'X Payout Guarantee — 3 Days',
    file: '/assets/x/payout-guarantee.png',
    category: 'X (Twitter)',
    description: 'Glass shield — paid in 3 days or extra $250. 16:9.',
  },
  {
    name: 'X Trade The News',
    file: '/assets/x/trade-the-news.png',
    category: 'X (Twitter)',
    description: 'Trading floor newsroom — glass chart erupting, no restrictions.',
  },
  {
    name: 'Payout Proof — $120K',
    file: '/assets/instagram/payout-proof.png',
    category: 'Instagram',
    description: 'Highest single payout flex post. Square 1:1.',
  },
  {
    name: 'Flash Sale 50% Off',
    file: '/assets/instagram/flash-sale-50.png',
    category: 'Instagram',
    description: '50% off promo with code FIRSTTPP. Square 1:1.',
  },
  {
    name: 'Instant Funding',
    file: '/assets/instagram/instant-funding.png',
    category: 'Instagram',
    description: 'No evaluation, trade real capital today. Square 1:1.',
  },
  {
    name: '90% Profit Split',
    file: '/assets/instagram/profit-split-90.png',
    category: 'Instagram',
    description: 'Keep up to 90% of your profits. Square 1:1.',
  },
  {
    name: 'Paid in Under 24 Hours',
    file: '/assets/instagram/payouts-24h.png',
    category: 'Instagram',
    description: 'Payout speed creative with trust stats. Square 1:1.',
  },
  {
    name: 'Get Funded up to $200K',
    file: '/assets/instagram/funding-200k.png',
    category: 'Instagram',
    description: 'Six account sizes from $59. Square 1:1.',
  },
  {
    name: 'One Step Challenge',
    file: '/assets/instagram/one-step-challenge.png',
    category: 'Instagram',
    description: 'One step, one target, funded. Square 1:1.',
  },
  {
    name: 'Scale Without Limits',
    file: '/assets/instagram/scale-without-limits.png',
    category: 'Instagram',
    description: 'Auto-scaling $25K to $200K. Square 1:1.',
  },
  {
    name: 'Discipline Pays',
    file: '/assets/instagram/discipline-pays.png',
    category: 'Instagram',
    description: 'Typography-driven motivational post. Square 1:1.',
  },
  {
    name: '100% Fee Refund',
    file: '/assets/instagram/fee-refund.png',
    category: 'Instagram',
    description: 'Full fee refund with first payout. Square 1:1.',
  },
  {
    name: 'Global Community',
    file: '/assets/instagram/global-community.png',
    category: 'Instagram',
    description: '10,000+ traders across 150+ countries. Square 1:1.',
  },
  {
    name: 'Start Your Journey — Brand Hero',
    file: '/assets/instagram/free-trial-brand.png',
    category: 'Instagram',
    description: '3D glass TPP logo hero post. Square 1:1.',
  },
  {
    name: 'Weekly Recap — $312K Rewards',
    file: '/assets/instagram/weekly-recap-rewards.png',
    category: 'Instagram',
    description: 'Trophy arena scene with weekly reward totals. Square 1:1.',
  },
  {
    name: 'Top Rewarded Countries',
    file: '/assets/instagram/top-rewarded-countries.png',
    category: 'Instagram',
    description: 'Interactive globe showing top countries and payouts. Square 1:1.',
  },
  {
    name: 'Red Card — Fast Payouts',
    file: '/assets/instagram/red-card-slow-payouts.png',
    category: 'Instagram',
    description: 'Meme-style comparison post. Square 1:1.',
  },
  {
    name: 'Free Retry — Second Chance',
    file: '/assets/instagram/free-retry-second-chance.png',
    category: 'Instagram',
    description: 'Glass refresh arrow in mist. Square 1:1.',
  },
  {
    name: 'Trade The News',
    file: '/assets/instagram/trade-the-news.png',
    category: 'Instagram',
    description: 'Candlestick chart breaking through clouds. Square 1:1.',
  },
  {
    name: 'Raw Spreads 0.0 Pips',
    file: '/assets/instagram/raw-spreads.png',
    category: 'Instagram',
    description: 'Speed tunnel with glass typography. Square 1:1.',
  },
  {
    name: 'TPP Terminal Platform',
    file: '/assets/instagram/tpp-terminal.png',
    category: 'Instagram',
    description: 'Trading screen in cloud penthouse. Square 1:1.',
  },
  {
    name: 'Refer and Earn',
    file: '/assets/instagram/refer-and-earn.png',
    category: 'Instagram',
    description: 'Interlinked glass rings. Square 1:1.',
  },
  {
    name: 'Fastest Payouts — Lightning',
    file: '/assets/instagram/fastest-payouts.png',
    category: 'Instagram',
    description: 'Giant lightning bolt on salt flat. Square 1:1.',
  },
  {
    name: 'Consistency Beats Luck',
    file: '/assets/instagram/consistency-beats-luck.png',
    category: 'Instagram',
    description: 'Trader walking path through clouds. Square 1:1.',
  },
  {
    name: 'New Era Coming — Teaser',
    file: '/assets/instagram/new-era-coming.png',
    category: 'Instagram',
    description: 'Epic mountain valley sunrise. Square 1:1.',
  },
  {
    name: 'Milestone — $2.5M Paid',
    file: '/assets/instagram/milestone-2-5m.png',
    category: 'Instagram',
    description: 'Celebratory plaza with milestone typography. Square 1:1.',
  },
  {
    name: 'Giveaway — Funded Accounts',
    file: '/assets/instagram/giveaway-funded-accounts.png',
    category: 'Instagram',
    description: 'Gift box floating in clouds. Square 1:1.',
  },
  {
    name: 'Trader Payout Story',
    file: '/assets/instagram/trader-payout-story.png',
    category: 'Instagram',
    description: 'Payout certificate card in gallery. Square 1:1.',
  },
  {
    name: 'Risk Management — Protect',
    file: '/assets/instagram/risk-management.png',
    category: 'Instagram',
    description: 'Glass shield in calm ocean. Square 1:1.',
  },
  {
    name: 'Join The Movement',
    file: '/assets/instagram/join-the-movement.png',
    category: 'Instagram',
    description: 'Amphitheater crowd facing TPP beacon. Square 1:1.',
  },
  {
    name: 'Payout Guarantee — 3 Days',
    file: '/assets/instagram/payout-guarantee-3days.png',
    category: 'Instagram',
    description: 'Paid within 3 business days or extra $250. Square 1:1.',
  },
  {
    name: 'Payout Guarantee — $7.2M',
    file: '/assets/instagram/payout-guarantee-total.png',
    category: 'Instagram',
    description: 'Trade, pass, get rewarded with request payout CTA. Square 1:1.',
  },
  {
    name: 'Funded Certificate',
    file: '/assets/instagram/funded-certificate.png',
    category: 'Instagram',
    description: 'Trader holding a funded certificate card. Square 1:1.',
  },
  {
    name: 'Trader Spotlight — $5,531',
    file: '/assets/instagram/trader-spotlight-payout.png',
    category: 'Instagram',
    description: 'Bold creator-thumbnail payout spotlight. Square 1:1.',
  },
  {
    name: 'Lifetime Total Payouts — $36M+',
    file: '/assets/instagram/lifetime-total-payouts.png',
    category: 'Instagram',
    description: 'Lifetime payouts with floating country reward cards. Square 1:1.',
  },
  {
    name: 'Start With Only $9',
    file: '/assets/instagram/start-with-only-9.png',
    category: 'Instagram',
    description: 'Low entry price hero with 3D glass typography. Square 1:1.',
  },
  {
    name: 'BOGO — Buy 1 Get 1 Free',
    file: '/assets/instagram/bogo-offer.png',
    category: 'Instagram',
    description: 'Chrome-lime BOGO offer with Get Offer CTA. Square 1:1.',
  },
  {
    name: 'Max Allocation — $400K',
    file: '/assets/instagram/max-allocation-400k.png',
    category: 'Instagram',
    description: 'Increased allocation on cliff peak with discount codes. Square 1:1.',
  },
  {
    name: 'Reward Split — 2 Payouts',
    file: '/assets/instagram/reward-split-two-payouts.png',
    category: 'Instagram',
    description: 'Trophy reward-split certificate with trader name. Square 1:1.',
  },
  {
    name: 'What\u2019s Inside a Funded Account',
    file: '/assets/instagram/whats-inside-account.png',
    category: 'Instagram',
    description: 'Think vs reality glass $200K breakdown. Square 1:1.',
  },
  {
    name: 'You Could Be Next',
    file: '/assets/instagram/you-could-be-next.png',
    category: 'Instagram',
    description: 'Reward spotlight card on stone ledge. Square 1:1.',
  },
  {
    name: 'Top 3 Rewarded Traders',
    file: '/assets/instagram/top-rewarded-traders.png',
    category: 'Instagram',
    description: 'Weekly top rewarded traders leaderboard. Square 1:1.',
  },
  {
    name: 'No Risk Rules. No Nonsense.',
    file: '/assets/instagram/no-nonsense-rules.png',
    category: 'Instagram',
    description: 'Mountain-peak flex offer with rule chips. Square 1:1.',
  },
  {
    name: '$1 Access',
    file: '/assets/instagram/one-dollar-access.png',
    category: 'Instagram',
    description: 'Quiz-result $1 starter match eligibility post. Square 1:1.',
  },
  {
    name: 'Capital for the Fearless',
    file: '/assets/instagram/capital-for-the-fearless.png',
    category: 'Instagram',
    description: 'Duotone brand portrait ad with Learn More bar. Square 1:1.',
  },
  {
    name: 'Giveaway — Tag 3 Traders',
    file: '/assets/instagram/giveaway-tag-3-friends.png',
    category: 'Instagram',
    description: '5x $10K funded accounts giveaway with tag mechanics. Square 1:1.',
  },
  {
    name: 'Red Flags vs Green Flags',
    file: '/assets/instagram/red-flags-green-flags.png',
    category: 'Instagram',
    description: 'Prop firm comparison — red flags vs TPP green flags. Square 1:1.',
  },
  {
    name: 'How Payouts Work — 3 Steps',
    file: '/assets/instagram/how-payouts-work.png',
    category: 'Instagram',
    description: 'Glass steps explaining the payout process. Square 1:1.',
  },
  {
    name: 'Myth vs Fact',
    file: '/assets/instagram/myth-vs-fact.png',
    category: 'Instagram',
    description: 'Myth-busting glass cards on prop firm payouts. Square 1:1.',
  },
  {
    name: '3 Rules of Trading Psychology',
    file: '/assets/instagram/trading-psychology-rules.png',
    category: 'Instagram',
    description: 'Glass head with lime brain — psychology rules. Square 1:1.',
  },
  {
    name: 'Your Road to Funded',
    file: '/assets/instagram/journey-to-funded.png',
    category: 'Instagram',
    description: 'Glass path to summit — trader journey roadmap. Square 1:1.',
  },
  {
    name: 'Ask Us Anything',
    file: '/assets/instagram/ask-us-anything.png',
    category: 'Instagram',
    description: 'Glass question mark AMA engagement post. Square 1:1.',
  },
]
